=== AlexanderAdelAU/Rule-Propagated-Service-Orchestration/btsn.common/RulePayLoad/rulepayload.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="rulepayload">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="header"/>
        <xs:element ref="targetservice"/>
         <xs:element ref="rulefiledata"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="header">
  <xs:complexType>
  		<xs:sequence>
  			<xs:element name="timestamp" type="xs:dateTime"></xs:element>
  			<xs:element name="ruleFileName" type="xs:string"/>
   			<xs:element name="ruleBaseVersion" type="xs:string" />
   			<xs:element name="ruleBaseCommitment" type="xs:string" />
  		</xs:sequence>
  	</xs:complexType>
  </xs:element>
  
   <xs:element name="targetservice">
  <xs:complexType>
  		<xs:sequence>
  			<xs:element name="serviceName" type="xs:string"></xs:element>
   			<xs:element name="operationName" type="xs:string" />
   			<xs:element name="businessService" type="xs:string" minOccurs="0" />
  		</xs:sequence>
  	</xs:complexType>
  </xs:element>
  
  <xs:element name="rulefiledata" >
    <xs:complexType>
      <xs:sequence>
        <xs:element name="data" type="xs:string"/>
         </xs:sequence>
    </xs:complexType>
  </xs:element>
 
</xs:schema>

=== AlexanderAdelAU/Rule-Propagated-Service-Orchestration/btsn.common/RulePayLoad/rulePayload_template.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><rulepayload xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rulepayload.xsd">
	<header>
		<timestamp>2012-01-02T20:05:05.491+10:30</timestamp>
		<ruleFileName>ThisServiceControlNode</ruleFileName>
		<ruleBaseVersion>v001</ruleBaseVersion>
		<ruleBaseCommitment>1</ruleBaseCommitment>
	</header>
	<targetservice>
		<serviceName>P1</serviceName>
		<operationName>processToken</operationName>
		<businessService>P1</businessService>
	</targetservice>
	<rulefiledata><data><![CDATA[<Atom><Rel>NodeType</Rel><Ind>EdgeNode</Ind></Atom>]]></data>
	</rulefiledata>
</rulepayload>
